name: 'Terraform EKS Pipeline'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: $AWS_REGION   # <-- Cambia a tu región AWS
  TF_VERSION: 1.7.4       # <-- Versión de Terraform que quieres usar
  TERRAFORM_DIR: ./terraform

jobs:
  terraform:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # Para autenticarse con AWS vía OIDC (sin claves)
      contents: read

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
        aws-region: ${{ env.AWS_REGION }}      

    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: 'Terraform Init'
      working-directory: ${{ env.TERRAFORM_DIR }}
      run: terraform init

    - name: 'Terraform Format Check'
      working-directory: ${{ env.TERRAFORM_DIR }}
      run: terraform fmt -check

    - name: 'Terraform Validate'
      working-directory: ${{ env.TERRAFORM_DIR }}
      run: terraform validate

    - name: 'Terraform Plan'
      working-directory: ${{ env.TERRAFORM_DIR }}
      run: terraform plan -out=tfplan

    - name: 'Terraform Apply'
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      working-directory: ${{ env.TERRAFORM_DIR }}
      run: terraform apply -auto-approve tfplan
